[package]
org = "tharmigan"
name = "service2"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "tharmigan"
name = "http"
version = "0.1.0"
repository = "local"
